/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Clases.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fernando
 */
public class PantallaPrincipalSocio extends javax.swing.JFrame {

    LoginVista login = new LoginVista();
    Usuario usuarioLogueado;
    
    public PantallaPrincipalSocio(Usuario usuarioLogueado) {
        initComponents();
        System.out.println(usuarioLogueado.toString());
        this.usuarioLogueado = usuarioLogueado;
        jLabelBienvenida.setText("Bienvenido a la aplicación, "+ usuarioLogueado.getNombreUsuario());
                        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLibros = new javax.swing.JMenu();
        jMenuItemBuscarLibro = new javax.swing.JMenuItem();
        jMenuEventos = new javax.swing.JMenu();
        jMenuItemEventosBuscar = new javax.swing.JMenuItem();
        jMenuClub = new javax.swing.JMenu();
        jMenuItemVerClubs = new javax.swing.JMenuItem();
        jMenuReservas = new javax.swing.JMenu();
        jMenuItemVerReservas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBienvenida.setText("Bienvenido a la Aplicación");

        jLabel1.setText("Imagen");

        jMenuLibros.setText("Libros");

        jMenuItemBuscarLibro.setText("Buscar");
        jMenuItemBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarLibroActionPerformed(evt);
            }
        });
        jMenuLibros.add(jMenuItemBuscarLibro);

        jMenuBar1.add(jMenuLibros);

        jMenuEventos.setText("Eventos");

        jMenuItemEventosBuscar.setText("Buscar");
        jMenuItemEventosBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEventosBuscarActionPerformed(evt);
            }
        });
        jMenuEventos.add(jMenuItemEventosBuscar);

        jMenuBar1.add(jMenuEventos);

        jMenuClub.setText("Club de Lectura");

        jMenuItemVerClubs.setText("Ver Clubs");
        jMenuItemVerClubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerClubsActionPerformed(evt);
            }
        });
        jMenuClub.add(jMenuItemVerClubs);

        jMenuBar1.add(jMenuClub);

        jMenuReservas.setText("Reservas");

        jMenuItemVerReservas.setText("Ver reservas");
        jMenuItemVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerReservasActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemVerReservas);

        jMenuBar1.add(jMenuReservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabelBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarLibroActionPerformed
        try {
            BuscarLibrosVista buscarLibros = new BuscarLibrosVista(this.usuarioLogueado);
            buscarLibros.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemBuscarLibroActionPerformed

    private void jMenuItemVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerReservasActionPerformed
        try {
            MisReservasVista reservasVista = new MisReservasVista(usuarioLogueado);
            reservasVista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemVerReservasActionPerformed

    private void jMenuItemEventosBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEventosBuscarActionPerformed
        try {
            EventosVista eventos = new EventosVista(this.usuarioLogueado);
            eventos.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEventosBuscarActionPerformed

    private void jMenuItemVerClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerClubsActionPerformed
        try {
            ClubVista clubVista = new ClubVista(this.usuarioLogueado);
            clubVista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemVerClubsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClub;
    private javax.swing.JMenu jMenuEventos;
    private javax.swing.JMenuItem jMenuItemBuscarLibro;
    private javax.swing.JMenuItem jMenuItemEventosBuscar;
    private javax.swing.JMenuItem jMenuItemVerClubs;
    private javax.swing.JMenuItem jMenuItemVerReservas;
    private javax.swing.JMenu jMenuLibros;
    private javax.swing.JMenu jMenuReservas;
    // End of variables declaration//GEN-END:variables
}
